In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from test_model import test_model
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sc_sharp import scSHARP
import utilities

In [3]:
grid_results = pd.read_csv("grid_search_sim_0.7_imbalance_output/combined.csv", header=None, index_col=0)
grid_results.columns = ["Total Accuracy", "Val Accuracy", "Test Accuracy", "Total SD", "Val SD", "Test SD", "Config", "Dropout", "Batch", "Neighbors"]
grid_results['GCN Layers'] = grid_results['Config'].apply(lambda x: x.split('_')[0])
grid_results['Final Embedding'] = grid_results['Config'].apply(lambda x: x.split('_')[1].split(".")[0])
grid_results['GCN Layers'] = pd.to_numeric(grid_results['GCN Layers'])
grid_results['Final Embedding'] = pd.to_numeric(grid_results['Final Embedding'])
grid_results.sort_values("Val Accuracy", ascending=False).head(10)

Total Accuracy  Val Accuracy  Test Accuracy  Total SD    Val SD  Test SD  \
0                                                                               
1          0.917918      0.935135            0.0  0.002585  0.013957      0.0   
91         0.916717      0.928649            0.0  0.001400  0.007559      0.0   
145        0.916517      0.927568            0.0  0.002415  0.013043      0.0   
127        0.916517      0.927568            0.0  0.001648  0.008900      0.0   
7          0.916016      0.924865            0.0  0.002472  0.013350      0.0   
151        0.915916      0.924324            0.0  0.002627  0.014187      0.0   
148        0.915816      0.923784            0.0  0.002134  0.011523      0.0   
97         0.915716      0.923243            0.0  0.002784  0.015032      0.0   
94         0.915716      0.923243            0.0  0.002939  0.015872      0.0   
4          0.915616      0.922703            0.0  0.001890  0.010208      0.0   

       Config  Dropout  Batch  Neighbors  GCN Layers  Final Embedding  
0                                                                      
1    2_25.txt      0.0     20          2           2               25  
91   2_40.txt      0.0     20          2           2               40  
145  2_60.txt      0.0     20          2           2               60  
127  2_15.txt      0.0     20          2           2               15  
7    2_25.txt      0.0     50          2           2               25  
151  2_60.txt      0.0     50          2           2               60  
148  2_60.txt      0.0     35          2           2               60  
97   2_40.txt      0.0     50          2           2               40  
94   2_40.txt      0.0     35          2           2               40  
4    2_25.txt      0.0     35          2           2               25

In [8]:
set(range(1,217))-set(grid_results.index.to_numpy())

set()

In [85]:
data_folders = ["/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/"]
tools = ["sctype","scsorter","scina", "singler", "scpred"]
votes_necessary = .51
model_file = "configs/2_25.txt"
neighbors = 2
batch_size=20
training_epochs=150
random_inits = 5
counts="query_counts.csv"
meta="query_meta.csv"
meta_col = "Group"

In [7]:
results = test_model(data_folders, tools, votes_necessary, model_file, neighbors, batch_size, training_epochs, random_inits, counts=counts, meta=meta, meta_col=meta_col)
results

Loss in epoch 0 = 53.265446
Loss in epoch 10 = 0.086855
Loss in epoch 20 = 0.019189
Loss in epoch 30 = 0.008448
Loss in epoch 40 = 0.003935
Loss in epoch 50 = 0.002211
Loss in epoch 60 = 0.002031
Loss in epoch 70 = 0.001345
Loss in epoch 80 = 0.000722
Loss in epoch 90 = 0.000388
Loss in epoch 100 = 0.000420
Loss in epoch 110 = 0.000255
Loss in epoch 120 = 0.000173
Loss in epoch 130 = 0.000144
Loss in epoch 140 = 0.000087
Loss in epoch 0 = 56.131859
Loss in epoch 10 = 0.094429
Loss in epoch 20 = 0.020094
Loss in epoch 30 = 0.008332
Loss in epoch 40 = 0.004352
Loss in epoch 50 = 0.002918
Loss in epoch 60 = 0.001444
Loss in epoch 70 = 0.000949
Loss in epoch 80 = 0.000783
Loss in epoch 90 = 0.000454
Loss in epoch 100 = 0.000402
Loss in epoch 110 = 0.000272
Loss in epoch 120 = 0.000217
Loss in epoch 130 = 0.000138
Loss in epoch 140 = 0.000096
Loss in epoch 0 = 54.562729
Loss in epoch 10 = 0.075778
Loss in epoch 20 = 0.021772
Loss in epoch 30 = 0.007878
Loss in epoch 40 = 0.003644
Loss in ep

/home/users/lewinsda/scSHARP/utilities.py:187: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


data_name            method  total_accuracy  \
0  splat_0.7_imbalance_031223               GCN        0.940340   
1  splat_0.7_imbalance_031223          Max Col.        0.917918   
2  splat_0.7_imbalance_031223  Confident Labels             NaN   
3  splat_0.7_imbalance_031223            sctype        0.752753   
4  splat_0.7_imbalance_031223          scsorter        0.870871   
5  splat_0.7_imbalance_031223             scina        0.703704   
6  splat_0.7_imbalance_031223           singler        0.913914   
7  splat_0.7_imbalance_031223            scpred        0.699700   
8  splat_0.7_imbalance_031223         Tool Avg.        0.788188   

   train_accuracy  test_accuracy  total_sd  train_sd   test_sd  
0        0.964478       0.620000  0.003053  0.000000  0.043566  
1        0.964478       0.300000  0.000000  0.000000  0.000000  
2        0.964478            NaN  0.000000  0.000000  0.000000  
3        0.790097       0.257143  0.000000  0.000000  0.000000  
4        0.889128       0.628571  0.000000  0.000000  0.000000  
5        0.749193       0.100000  0.000000  0.000000  0.000000  
6        0.933262       0.657143  0.000000  0.000000  0.000000  
7        0.744887       0.100000  0.000000  0.000000  0.000000  
8        0.821313       0.348571  0.098573  0.085364  0.276383

In [80]:
#running with same filtering
real_labels = pd.read_csv("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/query_meta.csv", index_col=0)['Group']
real_labels,_ = pd.factorize(real_labels, sort=True)
preds_df = pd.read_csv("preds_test_0.7_2", index_col=0)
preds_df

scina scsorter  sctype singler  scpred
Cell1001  Group3   Group3  Group3  Group3  Group3
Cell1002  Group4   Group4  Group2  Group4     NaN
Cell1003  Group1   Group1  Group1  Group1  Group1
Cell1004     NaN   Group4  Group2  Group4     NaN
Cell1005     NaN   Group1  Group1  Group1     NaN
...          ...      ...     ...     ...     ...
Cell1996  Group3   Group3  Group3  Group3  Group3
Cell1997  Group3   Group3  Group3  Group3  Group3
Cell1998  Group2   Group2  Group3  Group2  Group2
Cell1999  Group3   Group3  Group3  Group3  Group3
Cell2000  Group1   Group2  Group3  Group2  Group2

[999 rows x 5 columns]

In [81]:
scsorter,_ = pd.factorize(preds_df['scsorter'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.8709)

In [76]:
scsorter,_ = pd.factorize(preds_df['scsorter'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.8709)

In [82]:
scsorter,_ = pd.factorize(preds_df['scina'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.7037)

In [83]:
scsorter,_ = pd.factorize(preds_df['sctype'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.7528)

In [78]:
scsorter,_ = pd.factorize(preds_df['singler'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.9159)

In [79]:
scsorter,_ = pd.factorize(preds_df['scpred'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.7027)

In [5]:
data_path = "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/query_counts.csv"
tool_preds = "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/preds.csv"
tool_list = ["scina", "scsorter", "sctype", "singler", "scsorter"]
marker_path = "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/markers.txt"
neighbors=2
config="configs/2_25.txt"
sharp = scSHARP(data_path, tool_preds, tool_list, marker_path, neighbors, config)

In [6]:
preds, train_nodes, test_nodes, keep_cells = sharp.run_prediction(training_epochs=1, thresh=0.51, batch_size=20, seed=8)

Loss in epoch 0 = 52.334377


In [41]:
preds, train_nodes, test_nodes, keep_cells = sharp.run_prediction(training_epochs=150, thresh=0.51, batch_size=20, seed=8)

Loss in epoch 0 = 52.334377
Loss in epoch 10 = 0.075407
Loss in epoch 20 = 0.015976
Loss in epoch 30 = 0.006336
Loss in epoch 40 = 0.004460
Loss in epoch 50 = 0.002150
Loss in epoch 60 = 0.001633
Loss in epoch 70 = 0.000847
Loss in epoch 80 = 0.000640
Loss in epoch 90 = 0.000523
Loss in epoch 100 = 0.000405
Loss in epoch 110 = 0.000216
Loss in epoch 120 = 0.000216
Loss in epoch 130 = 0.000139
Loss in epoch 140 = 0.000077


In [42]:
sharp.counts.shape

(1000, 33694)

In [43]:
utilities.preprocess(np.array(sharp.counts), scale=False, run_pca=False)[0].shape

(999, 16507)

In [6]:
real_labels = pd.read_csv("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/query_meta.csv", index_col=0)['Group']
real_labels,_ = pd.factorize(real_labels, sort=True)

In [9]:
results = utilities.validation_metrics(torch.tensor(real_labels[keep_cells]), preds.cpu(), train_nodes, test_nodes)
results

(0.9419419169425964,
 array([[361,   8,   4,   0],
        [  0, 318,   0,   0],
        [  4,   4, 196,   0],
        [  8,  19,  11,  66]]),
 0.9644779562950134,
 array([[340,   8,   3,   0],
        [  0, 318,   0,   0],
        [  4,   4, 191,   0],
        [  2,   8,   4,  47]]),
 0.6428571343421936,
 array([[21,  0,  1,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  5,  0],
        [ 6, 11,  7, 19]]))

In [10]:
preds_df = pd.read_csv("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/preds.csv", index_col=0)
preds_df

scina scsorter  sctype singler  scpred
Cell1001  Group3   Group3  Group3  Group3  Group3
Cell1002  Group4   Group4  Group2  Group4     NaN
Cell1003  Group1   Group1  Group1  Group1  Group1
Cell1004     NaN   Group4  Group2  Group4     NaN
Cell1005     NaN   Group1  Group1  Group1     NaN
...          ...      ...     ...     ...     ...
Cell1996  Group3   Group3  Group3  Group3  Group3
Cell1997  Group3   Group3  Group3  Group3  Group3
Cell1998  Group2   Group2  Group3  Group2  Group2
Cell1999  Group3   Group3  Group3  Group3  Group3
Cell2000  Group1   Group2  Group3  Group2  Group2

[999 rows x 5 columns]

In [23]:
scsorter,_ = pd.factorize(preds_df['scsorter'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.8709)

In [11]:
grid_results = pd.read_csv("grid_search_sim_0.8_imbalance_output/combined.csv", header=None, index_col=0)
grid_results.columns = ["Total Accuracy", "Val Accuracy", "Test Accuracy", "Total SD", "Val SD", "Test SD", "Config", "Dropout", "Batch", "Neighbors"]
grid_results['GCN Layers'] = grid_results['Config'].apply(lambda x: x.split('_')[0])
grid_results['Final Embedding'] = grid_results['Config'].apply(lambda x: x.split('_')[1].split(".")[0])
grid_results['GCN Layers'] = pd.to_numeric(grid_results['GCN Layers'])
grid_results['Final Embedding'] = pd.to_numeric(grid_results['Final Embedding'])
grid_results.sort_values("Val Accuracy", ascending=False).head(10)

Total Accuracy  Val Accuracy  Test Accuracy  Total SD    Val SD  Test SD  \
0                                                                               
1          0.969970      0.979381            0.0  0.001828  0.009411      0.0   
127        0.969870      0.978866            0.0  0.001597  0.008222      0.0   
145        0.969870      0.978866            0.0  0.002285  0.011767      0.0   
91         0.969770      0.978351            0.0  0.002488  0.012812      0.0   
40         0.969670      0.977835            0.0  0.002005  0.010324      0.0   
37         0.969570      0.977320            0.0  0.002415  0.012438      0.0   
43         0.969269      0.975773            0.0  0.002005  0.010324      0.0   
4          0.969269      0.975773            0.0  0.001496  0.007703      0.0   
109        0.968969      0.974227            0.0  0.002792  0.014376      0.0   
7          0.968969      0.974227            0.0  0.001156  0.005952      0.0   

       Config  Dropout  Batch  Neighbors  GCN Layers  Final Embedding  
0                                                                      
1    2_25.txt      0.0     20          2           2               25  
127  2_15.txt      0.0     20          2           2               15  
145  2_60.txt      0.0     20          2           2               60  
91   2_40.txt      0.0     20          2           2               40  
40   3_60.txt      0.0     35          2           3               60  
37   3_60.txt      0.0     20          2           3               60  
43   3_60.txt      0.0     50          2           3               60  
4    2_25.txt      0.0     35          2           2               25  
109  3_40.txt      0.0     20          2           3               40  
7    2_25.txt      0.0     50          2           2               25

In [12]:
set(range(1,217))-set(grid_results.index.to_numpy())

set()

In [13]:
data_folders = ["/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/"]
tools = ["sctype","scsorter","scina", "singler", "scpred"]
votes_necessary = .51
model_file = "configs/2_25.txt"
neighbors = 2
batch_size=20
training_epochs=150
random_inits = 5
counts="query_counts.csv"
meta="query_meta.csv"
meta_col = "Group"

In [14]:
results = test_model(data_folders, tools, votes_necessary, model_file, neighbors, batch_size, training_epochs, random_inits, counts=counts, meta=meta, meta_col=meta_col)
results

Loss in epoch 0 = 52.166740
Loss in epoch 10 = 0.043182
Loss in epoch 20 = 0.013754
Loss in epoch 30 = 0.006515
Loss in epoch 40 = 0.003251
Loss in epoch 50 = 0.001683
Loss in epoch 60 = 0.001051
Loss in epoch 70 = 0.000718
Loss in epoch 80 = 0.000507
Loss in epoch 90 = 0.000437
Loss in epoch 100 = 0.000271
Loss in epoch 110 = 0.000203
Loss in epoch 120 = 0.000157
Loss in epoch 130 = 0.000099
Loss in epoch 140 = 0.000079
Loss in epoch 0 = 54.234356
Loss in epoch 10 = 0.054442
Loss in epoch 20 = 0.012416
Loss in epoch 30 = 0.006270
Loss in epoch 40 = 0.003407
Loss in epoch 50 = 0.002337
Loss in epoch 60 = 0.001097
Loss in epoch 70 = 0.000862
Loss in epoch 80 = 0.000557
Loss in epoch 90 = 0.000408
Loss in epoch 100 = 0.000315
Loss in epoch 110 = 0.000224
Loss in epoch 120 = 0.000162
Loss in epoch 130 = 0.000104
Loss in epoch 140 = 0.000079
Loss in epoch 0 = 53.106033
Loss in epoch 10 = 0.052936
Loss in epoch 20 = 0.012877
Loss in epoch 30 = 0.005062
Loss in epoch 40 = 0.003206
Loss in ep

/home/users/lewinsda/scSHARP/utilities.py:187: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


data_name            method  total_accuracy  \
0  splat_0.8_imbalance_031223               GCN        0.995395   
1  splat_0.8_imbalance_031223          Max Col.        0.980981   
2  splat_0.8_imbalance_031223  Confident Labels             NaN   
3  splat_0.8_imbalance_031223            sctype        0.953954   
4  splat_0.8_imbalance_031223          scsorter        0.953954   
5  splat_0.8_imbalance_031223             scina        0.748749   
6  splat_0.8_imbalance_031223           singler        0.954955   
7  splat_0.8_imbalance_031223            scpred        0.797798   
8  splat_0.8_imbalance_031223         Tool Avg.        0.881882   

   train_accuracy  test_accuracy  total_sd  train_sd   test_sd  
0        0.997944       0.900000  0.001141  0.000000  0.043853  
1        0.997944       0.346154  0.000000  0.000000  0.000000  
2        0.997944            NaN  0.000000  0.000000  0.000000  
3        0.968140       0.423077  0.000000  0.000000  0.000000  
4        0.958890       0.769231  0.000000  0.000000  0.000000  
5        0.767729       0.038462  0.000000  0.000000  0.000000  
6        0.964029       0.615385  0.000000  0.000000  0.000000  
7        0.817061       0.076923  0.000000  0.000000  0.000000  
8        0.895170       0.384615  0.100652  0.095484  0.322940

In [51]:
#running with same filtering
real_labels = pd.read_csv("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/query_meta.csv", index_col=0)['Group']
real_labels,_ = pd.factorize(real_labels, sort=True)
preds_df = pd.read_csv("preds_test_0.8", index_col=0)
preds_df

scina scsorter  sctype singler  scpred
Cell1001  Group3   Group3  Group3  Group3  Group3
Cell1002     NaN   Group4  Group4  Group4  Group4
Cell1003  Group1   Group1  Group1  Group1  Group1
Cell1004  Group4   Group4  Group4  Group2  Group1
Cell1005  Group1   Group1  Group1  Group1  Group1
...          ...      ...     ...     ...     ...
Cell1996  Group3   Group3  Group3  Group3  Group3
Cell1997  Group3   Group3  Group3  Group3  Group3
Cell1998  Group2   Group2  Group2  Group2  Group2
Cell1999  Group1   Group3  Group3  Group3     NaN
Cell2000  Group2   Group2  Group2  Group2     NaN

[999 rows x 5 columns]

In [52]:
scsorter,_ = pd.factorize(preds_df['sctype'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.9510)

In [22]:
data_path = "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/query_counts.csv"
tool_preds = "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/preds.csv"
tool_list = ["scina", "scsorter", "sctype", "singler", "scsorter"]
marker_path = "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/markers.txt"
neighbors=2
config="configs/2_25.txt"
sharp = scSHARP(data_path, tool_preds, tool_list, marker_path, neighbors, config)

In [23]:
preds, train_nodes, test_nodes, keep_cells = sharp.run_prediction(training_epochs=1, thresh=0.51, batch_size=20, seed=8)

Loss in epoch 0 = 51.410789


In [25]:
preds, train_nodes, test_nodes, keep_cells = sharp.run_prediction(training_epochs=150, thresh=0.51, batch_size=20, seed=8)

Loss in epoch 0 = 51.410797
Loss in epoch 10 = 0.065694
Loss in epoch 20 = 0.013037
Loss in epoch 30 = 0.005329
Loss in epoch 40 = 0.003156
Loss in epoch 50 = 0.001926
Loss in epoch 60 = 0.001043
Loss in epoch 70 = 0.000709
Loss in epoch 80 = 0.000594
Loss in epoch 90 = 0.000386
Loss in epoch 100 = 0.000311
Loss in epoch 110 = 0.000215
Loss in epoch 120 = 0.000177
Loss in epoch 130 = 0.000110
Loss in epoch 140 = 0.000091


In [34]:
sharp.counts.shape

(1000, 33694)

In [38]:
utilities.preprocess(np.array(sharp.counts), scale=False, run_pca=False)[0].shape

(999, 16408)

In [26]:
real_labels = pd.read_csv("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/query_meta.csv", index_col=0)['Group']
real_labels,_ = pd.factorize(real_labels, sort=True)

In [27]:
results = utilities.validation_metrics(torch.tensor(real_labels[keep_cells]), preds.cpu(), train_nodes, test_nodes)
results

(0.9939939975738525,
 array([[373,   0,   0,   0],
        [  0, 318,   0,   0],
        [  1,   0, 203,   0],
        [  2,   3,   0,  99]]),
 0.9979444742202759,
 array([[368,   0,   0,   0],
        [  0, 315,   0,   0],
        [  1,   0, 200,   0],
        [  0,   1,   0,  88]]),
 0.8461538553237915,
 array([[ 5,  0,  0,  0],
        [ 0,  3,  0,  0],
        [ 0,  0,  3,  0],
        [ 2,  2,  0, 11]]))

In [58]:
preds_df = pd.read_csv("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/preds.csv", index_col=0)
preds_df.head(10)

scina scsorter  sctype singler  scpred
Cell1001  Group3   Group3  Group3  Group3  Group3
Cell1002     NaN   Group4  Group4  Group4  Group4
Cell1003  Group1   Group1  Group1  Group1  Group1
Cell1004  Group4   Group4  Group4  Group2  Group1
Cell1005  Group1   Group1  Group1  Group1  Group1
Cell1006     NaN   Group1  Group1  Group1  Group1
Cell1007  Group1   Group1  Group1  Group1  Group1
Cell1008  Group4   Group4  Group1  Group4  Group3
Cell1009  Group3   Group3  Group3  Group3  Group3
Cell1010  Group2   Group2  Group2  Group2  Group2

In [62]:
scsorter,_ = pd.factorize(preds_df['sctype'], sort=True)
(torch.Tensor(scsorter) == torch.Tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean()

tensor(0.9540)

In [63]:
scsorter,_ = pd.factorize(preds_df['sctype'], sort=True)
(torch.Tensor(scsorter)[test_nodes] == torch.Tensor(real_labels[keep_cells][test_nodes])).type(torch.FloatTensor).mean()

tensor(0.4231)

In [46]:
(preds_df['sctype'].compare(preds_df['scsorter']))

self   other
Cell1008  Group1  Group4
Cell1036  Group1  Group2
Cell1047  Group4  Group2
Cell1061  Group1  Group4
Cell1064  Group3  Group1
...          ...     ...
Cell1938  Group1  Group3
Cell1969  Group1  Group3
Cell1973  Group2  Group4
Cell1982  Group1  Group4
Cell1992  Group3  Group1

[90 rows x 2 columns]

In [31]:
float((torch.tensor(scsorter) == torch.tensor(real_labels[keep_cells])).type(torch.FloatTensor).mean().numpy())

0.9539539813995361

In [44]:
# non parametric results
data_sets = ["/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/","/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/"]

for data_path in data_sets:
    print(data_path)
    counts = pd.read_csv(data_path + "query_counts.csv", index_col = 0)
    X, keep_cells,keep_genes,pca_obj = utilities.preprocess(np.array(counts), scale=False, run_pca=True)
    print(X.shape)
    _,marker_names = utilities.read_marker_file(data_path + "markers.txt")
    all_labels = pd.read_csv(data_path + "preds.csv", index_col=0)
    all_labels_factored = utilities.factorize_df(all_labels, marker_names)
    encoded_labels = utilities.encode_predictions(all_labels_factored)
    confident_labels = utilities.get_consensus_labels(encoded_labels, necessary_vote = .51)
    train_nodes = np.where(confident_labels != -1)[0]
    test_nodes = np.where(confident_labels == -1)[0]
    real_y = pd.read_csv(data_path + "query_meta.csv", index_col= 0).Group
    real_y = pd.factorize(real_y, sort=True)[0]
    real_y = real_y[keep_cells]
    
    if data_path == "/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/":
        neighbors = 50
    else: neighbors = 100
    
    print(neighbors)
    
    preds = utilities.knn_consensus_batch(X, confident_labels, neighbors, converge=True, one_epoch=False, batch_size=1000, keep_conf=True)
    print(utilities.validation_metrics(torch.tensor(real_y), torch.tensor(preds), train_nodes, test_nodes))

/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_imbalance_031223/
(999, 500)
50
1


/home/users/lewinsda/scSHARP/utilities.py:423: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  dataset  = torch.utils.data.TensorDataset(torch.tensor(counts), torch.tensor(preds))


(0.9209209084510803, array([[359,  11,   3,   0],
       [  0, 318,   0,   0],
       [  4,   4, 196,   0],
       [  6,  40,  11,  47]]), 0.9644779562950134, array([[340,   8,   3,   0],
       [  0, 318,   0,   0],
       [  4,   4, 191,   0],
       [  2,   8,   4,  47]]), 0.34285715222358704, array([[19,  3,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  5,  0],
       [ 4, 32,  7,  0]]))
/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_imbalance_031223/
(999, 500)
100
(0.9809809923171997, array([[371,   1,   1,   0],
       [  0, 318,   0,   0],
       [  1,   0, 203,   0],
       [  0,  15,   1,  88]]), 0.9979444742202759, array([[368,   0,   0,   0],
       [  0, 315,   0,   0],
       [  1,   0, 200,   0],
       [  0,   1,   0,  88]]), 0.3461538553237915, array([[ 3,  1,  1,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  3,  0],
       [ 0, 14,  1,  0]]))
