In [2]:
import utilities
import numpy as np
import pandas as pd
from itertools import combinations
from sklearn.metrics import pairwise_distances

In [30]:
def disimilarity_new(X, group_1, group_2):
    group_1 = np.array(group_1)
    group_2 = np.array(group_2)
    print(len(group_1))
    dist = pairwise_distances(X)
    print(dist)
    sub_dist = dist[group_1, group_2]
    print(sub_dist)
    total = np.sum(sub_dist)
    print(total)
    return total / (group_1.sum() * group_2.sum())
    
    
    

In [16]:
X = np.array([[1,1,1],[2,2,2],[3,3,3]])
disimilarity_new(X, [True, False, True], [False, True, False])

[[0.         1.73205081 3.46410162]
 [1.73205081 0.         1.73205081]
 [3.46410162 1.73205081 0.        ]]
[1.73205081 1.73205081]
3.4641016151377544


1.7320508075688772

In [8]:
 utilities.average_linkage(np.array([[1,1,1], [3,3,3]]), np.array([[2,2,2]]))

1.7320508075688772

In [31]:
def compare_cell_clusters(data_folder, counts, meta, meta_col):
    # read in dataset
    data_path = data_folder + counts
    X = pd.read_csv(data_path, index_col=0)
    X, keep_cells,_,_ = utilities.preprocess(np.array(X), scale=False)
    meta_path = data_folder + meta
    metadata = pd.read_csv(meta_path, index_col=0)
    if type(meta_col)==int:
        real_y, key = pd.factorize(metadata.iloc[:,meta_col], sort=True)
    else: real_y, key = pd.factorize(metadata[meta_col], sort=True)
    real_y = real_y[keep_cells]
    
    for combo in combinations(np.unique(real_y),2):
        #disimilarity = utilities.average_linkage(X[real_y == combo[0]], X[real_y == combo[1]])
        disimilarity = disimilarity_new(X, real_y == combo[0], real_y == combo[1])
        print(str(key[combo[0]]) + " and " + str(key[combo[1]]) + " = " + str(disimilarity))
        
    print(key)
    return X, real_y

In [34]:
dist = pairwise_distances(X)

In [35]:
dist.shape

(692, 692)

In [39]:
(real_y==1).shape

(692,)

In [36]:
dist[real_y==0, real_y==1]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (244,) (156,) 

In [32]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/jung/", 'counts.csv', 'labels.csv', 0)

692
[[ 0.       39.220417 50.39939  ... 67.4028   79.62719  78.85395 ]
 [39.220417  0.       47.399456 ... 64.45823  78.15358  78.75876 ]
 [50.39939  47.399456  0.       ... 70.19003  80.61039  80.540245]
 ...
 [67.4028   64.45823  70.19003  ...  0.       83.288445 83.17234 ]
 [79.62719  78.15358  80.61039  ... 83.288445  0.       70.954414]
 [78.85395  78.75876  80.540245 ... 83.17234  70.954414  0.      ]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (244,) (156,) 

In [33]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/jung/", 'counts.csv', 'labels.csv', 0)

spc and spd = 73.88623989455186
spc and spg = 81.22526369768396
spd and spg = 82.85252243550484
Index(['spc', 'spd', 'spg'], dtype='object')


In [32]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.7_de_rq/", 'query_counts.csv', 'query_meta.csv', "Group")

Group1 and Group2 = 43.03840230729052
Group1 and Group3 = 42.87681787266156
Group1 and Group4 = 41.65165749806866
Group2 and Group3 = 43.13969845362546
Group2 and Group4 = 41.908186184949166
Group3 and Group4 = 41.69884955141725
Index(['Group1', 'Group2', 'Group3', 'Group4'], dtype='object')


In [34]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_de_rq/", 'query_counts.csv', 'query_meta.csv', "Group")

Group1 and Group2 = 43.433500149580254
Group1 and Group3 = 43.08833691801796
Group1 and Group4 = 41.663929044566274
Group2 and Group3 = 43.46095330551942
Group2 and Group4 = 42.058046933917865
Group3 and Group4 = 41.59050578730638
Index(['Group1', 'Group2', 'Group3', 'Group4'], dtype='object')


In [35]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_de_rq/", 'query_counts.csv', 'query_meta.csv', "Group")

Group1 and Group2 = 43.43349771633815
Group1 and Group3 = 43.088334649695426
Group1 and Group4 = 41.66392728654438
Group2 and Group3 = 43.46095138971003
Group2 and Group4 = 42.058045347130154
Group3 and Group4 = 41.59050424668158
Index(['Group1', 'Group2', 'Group3', 'Group4'], dtype='object')


In [37]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.3_de_rq_103122/", 'query_counts.csv', 'query_meta.csv', "Group")

Group1 and Group2 = 44.82626442378252
Group1 and Group3 = 44.83444169183506
Group1 and Group4 = 44.75475300480137
Group2 and Group3 = 44.92729778925871
Group2 and Group4 = 44.828342446496436
Group3 and Group4 = 44.8283992729658
Index(['Group1', 'Group2', 'Group3', 'Group4'], dtype='object')


In [38]:
X, real_y = compare_cell_clusters("/home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.9_de_rq_103122/", 'query_counts.csv', 'query_meta.csv', "Group")

Group1 and Group2 = 45.861992683203624
Group1 and Group3 = 45.79678448501366
Group1 and Group4 = 45.45277033793568
Group2 and Group3 = 46.091879768126375
Group2 and Group4 = 45.659266812069994
Group3 and Group4 = 45.61782638776969
Index(['Group1', 'Group2', 'Group3', 'Group4'], dtype='object')


In [17]:
for combo in combinations([0,1,2], 2):
    print(combo)

(0, 1)
(0, 2)
(1, 2)


In [11]:
real_y

array([2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 1, 2, 2, 0, 2, 0, 2, 0, 2,
       1, 2, 2, 0, 0, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 2, 0, 2, 0, 2, 2, 2, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1,
       2, 2, 2, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 2, 0,
       0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0,
       1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 2, 2, 1, 2, 0, 2, 1, 2, 2,
       0, 2, 0, 1, 2, 2, 2, 2, 0, 0, 1, 2, 0, 2, 1, 0, 0, 2, 0, 2, 0, 0,
       0, 1, 0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 2, 2,
       1, 1, 2, 2, 2, 2, 0, 2, 2, 1, 1, 0, 2, 0, 2, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 2, 2, 0, 1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 2, 0, 1, 1, 2,
       1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 0,
       0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 0, 0, 1, 2, 2, 0, 1, 1, 2, 0,
       2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 0, 1, 1, 2,

In [13]:
X[real_y==0]

array([[-14.185537  ,  -7.458223  ,   8.384081  , ...,  -0.1183617 ,
         -0.58229095,   1.5128574 ],
       [-15.797154  , -13.1198225 ,   5.4865193 , ...,   1.193898  ,
          1.3348278 ,   0.98085797],
       [ -1.5621954 , -10.570117  ,  -4.47332   , ...,   1.0716755 ,
         -1.2324159 ,  -0.64864415],
       ...,
       [-11.904461  , -11.370434  ,   6.843371  , ...,  -0.32835588,
          2.4064457 ,  -0.36809808],
       [-13.625015  , -10.563273  ,   5.9214606 , ...,  -1.1095074 ,
          0.36168855,   0.94928414],
       [-14.012843  , -12.057545  ,   4.094969  , ...,  -1.2905434 ,
         -0.7926164 ,  -0.35491347]], dtype=float32)