In [1]:
import numpy as np
import pandas as pd
import torch
from gcn_model import GCNModel
import utilities

In [19]:
data_folder = "simulations/splat_0.15_de_rq/"

In [20]:
# get labels
data_path = data_folder + "query_counts.csv"
tools = ["sctype","scsorter","scina","singler", "scpred"]
ref_path = data_folder + "ref_counts.csv"
ref_label_path = data_folder + "ref_labels.csv"
marker_path = data_folder + "markers.txt"
all_labels = utilities.label_counts(data_path,tools,ref_path,ref_label_path,marker_path)

R[write to console]: Performing log-normalization

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to conso

Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 1000
Number of edges: 38247

Running Louvain algorithm...


R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: 

Maximum modularity in 10 random starts: 0.4637
Number of communities: 4
Elapsed time: 0 seconds


R[write to console]: Performing log-normalization

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to conso

●  Extracting feature space for each cell type...
  |                                                  | 0 % ~calculating   |+++++++++++++                                     | 25% ~01s           |+++++++++++++++++++++++++                         | 50% ~00s           |++++++++++++++++++++++++++++++++++++++            | 75% ~00s           |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
DONE!
●  Training models for each cell type...
  |                                                  | 0 % ~calculating   |+++++++++++++                                     | 25% ~23s           |+++++++++++++++++++++++++                         | 50% ~13s           |++++++++++++++++++++++++++++++++++++++            | 75% ~06s           |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=22s  
DONE!
●  Matching reference with new dataset...
	 ─ 2000 features present in reference loadings
	 ─ 2000 features shared between reference and new dataset
	 ─ 100% of features in 

R[write to console]: Harmony 1/20

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write t

●  Classifying cells...
DONE!


In [21]:
all_labels

scina scsorter  sctype singler  scpred
Cell1001  Group1   Group1  Group1  Group1  Group1
Cell1002  Group1   Group3  Group2  Group3  Group1
Cell1003  Group2   Group2  Group2  Group2  Group2
Cell1004  Group1   Group2  Group3  Group2    None
Cell1005  Group2   Group2  Group2  Group2    None
...          ...      ...     ...     ...     ...
Cell1996  Group3   Group3  Group2  Group3  Group3
Cell1997  Group1   Group1  Group1  Group1  Group1
Cell1998  Group4   Group4  Group3  Group4  Group1
Cell1999  Group1   Group1  Group1  Group1  Group1
Cell2000  Group4   Group4  Group2  Group4  Group3

[1000 rows x 5 columns]

In [22]:
_,marker_names = utilities.read_marker_file(marker_path)
marker_names

['Group1', 'Group2', 'Group3', 'Group4']

In [23]:
all_labels['sctype'].unique()

array(['Group1', 'Group2', 'Group3', None], dtype=object)

In [44]:
all_labels['sctype']

Cell1001    Group1
Cell1002    Group2
Cell1003    Group2
Cell1004    Group3
Cell1005    Group2
             ...  
Cell1996    Group2
Cell1997    Group1
Cell1998    Group3
Cell1999    Group1
Cell2000    Group2
Name: sctype, Length: 1000, dtype: object

In [45]:
all_labels_factored['sctype'] == -1

0      0
1      1
2      1
3      2
4      1
      ..
995    1
996    0
997    2
998    0
999    1
Name: sctype, Length: 1000, dtype: int64

In [24]:
all_labels_factored = utilities.factorize_df(all_labels, marker_names)
encoded_labels = utilities.encode_predictions(all_labels_factored)
encoded_labels

array([[5., 0., 0., 0.],
       [2., 1., 2., 0.],
       [0., 5., 0., 0.],
       ...,
       [1., 0., 1., 3.],
       [5., 0., 0., 0.],
       [0., 1., 1., 3.]])

In [25]:
# read in dataset
X = pd.read_csv(data_path, index_col=0)
X = utilities.preprocess(np.array(X), scale=False)
X.shape

(1000, 500)

In [26]:
meta_path = data_folder + "query_meta.csv"
metadata = pd.read_csv(meta_path, index_col=0)
real_y = pd.factorize(metadata['Group'], sort=True)[0]
real_y.shape

(1000,)

In [27]:
print(utilities.pred_accuracy(all_labels_factored['scina'], real_y))
print(utilities.pred_accuracy(all_labels_factored['sctype'], real_y))
print(utilities.pred_accuracy(all_labels_factored['scsorter'], real_y))
print(utilities.pred_accuracy(all_labels_factored['singler'], real_y))
print(utilities.pred_accuracy(all_labels_factored['scpred'], real_y))


0.9369999766349792
0.5590000152587891
0.8230000138282776
0.8700000047683716
0.7039999961853027


In [28]:
max_pred = torch.tensor(encoded_labels).max(dim=1)[1]
utilities.pred_accuracy(max_pred, real_y)

/Users/daniel/Desktop/conradLab/thesis/scSHARP/utilities.py:168: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


0.9599999785423279

In [29]:
confident_labels = utilities.get_consensus_labels(encoded_labels, necessary_vote = 3)
confident_labels

array([ 0., -1.,  1., -1.,  1.,  2.,  0.,  0., -1.,  2.,  0.,  2.,  0.,
        0.,  0.,  1.,  3.,  3.,  0.,  1.,  2.,  1.,  0.,  3.,  0.,  1.,
        1.,  3.,  3.,  3.,  2., -1.,  0.,  0.,  1.,  0.,  0.,  1.,  3.,
        1.,  2.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  2.,  0.,
        0.,  0.,  1.,  2.,  1.,  0.,  0.,  0.,  2.,  3.,  3.,  0.,  2.,
        1.,  0.,  0.,  3.,  2.,  0.,  0.,  1.,  0.,  2.,  0.,  0.,  0.,
       -1.,  0.,  2.,  0.,  1.,  2., -1.,  3.,  2.,  1.,  1.,  1.,  0.,
        3.,  3.,  0.,  0., -1., -1.,  2., -1.,  0.,  0., -1.,  2.,  0.,
        0.,  2., -1.,  2.,  1., -1.,  0., -1.,  1.,  1.,  0.,  3.,  0.,
        3.,  0.,  2.,  0.,  0.,  3.,  2.,  1.,  0.,  2.,  3., -1.,  2.,
        0.,  0.,  2.,  1.,  2., -1.,  0.,  0.,  3., -1.,  0.,  0.,  0.,
        2.,  0.,  0.,  1.,  2.,  0.,  0.,  0.,  3.,  0.,  3.,  1.,  2.,
        0.,  0.,  0.,  0.,  2.,  0.,  0.,  2.,  1.,  1.,  2.,  1.,  0.,
        1.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  2.,  0.,  3.,  0

In [30]:
train_nodes = np.where(confident_labels != -1)[0]
test_nodes = np.where(confident_labels == -1)[0]
print(np.unique(confident_labels))
print(np.unique(confident_labels[train_nodes]))
print(np.unique(confident_labels[test_nodes]))

[-1.  0.  1.  2.  3.]
[0. 1. 2. 3.]
[-1.]


In [31]:
print(utilities.pred_accuracy(confident_labels[train_nodes], real_y[train_nodes]))

0.984581470489502


In [33]:
# tool accuracy on test
print(utilities.pred_accuracy(np.array(all_labels_factored['scina'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['sctype'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['scsorter'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['singler'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['scpred'][test_nodes]), real_y[test_nodes]))
max_pred = torch.tensor(encoded_labels).max(dim=1)[1]
print(utilities.pred_accuracy(max_pred[test_nodes], real_y[test_nodes]))

0.6413043737411499
0.14130434393882751
0.44565218687057495
0.489130437374115
0.14130434393882751
0.717391312122345


/Users/daniel/Desktop/conradLab/thesis/scSHARP/utilities.py:168: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


In [34]:
dataset  = torch.utils.data.TensorDataset(torch.tensor(X), torch.tensor(confident_labels))
dataloader = torch.utils.data.DataLoader(dataset, batch_size=35, shuffle=True)

test_dataset  = torch.utils.data.TensorDataset(torch.tensor(X), torch.tensor(real_y))
test_dataloader = torch.utils.data.DataLoader(test_dataset, batch_size=35, shuffle=False)

In [38]:
m = GCNModel("configs/semi_basic_linear.txt", 2)

In [42]:
m.train(dataloader, 100)

Loss in epoch 0 = 0.001350
Loss in epoch 10 = 0.001173
Loss in epoch 20 = 0.000822
Loss in epoch 30 = 0.001282
Loss in epoch 40 = 0.000782
Loss in epoch 50 = 0.000579
Loss in epoch 60 = 0.000591
Loss in epoch 70 = 0.000399
Loss in epoch 80 = 0.000331
Loss in epoch 90 = 0.000211


In [43]:
m.validation_metrics(test_dataloader, train_nodes, test_nodes)

(0.972000002861023,
 array([[428,   2,   1,   0],
        [  5, 205,   3,   0],
        [  0,   0, 228,   1],
        [  3,   8,   5, 111]]),
 0.984581470489502,
 array([[391,   1,   0,   0],
        [  1, 193,   3,   0],
        [  0,   0, 224,   1],
        [  1,   3,   4,  86]]),
 0.8478260636329651,
 array([[37,  1,  1,  0],
        [ 4, 12,  0,  0],
        [ 0,  0,  4,  0],
        [ 2,  5,  1, 25]]))