In [1]:
import numpy as np
import pandas as pd
import torch
from gcn_model import GCNModel
import utilities
from test_model import test_model
import os

/home/users/lewinsda/.conda/envs/daniel_thesis_2/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
#data_folder = "/home/groups/ConradLab/daniel/sharp_sims/splat_0.7_de_rq/"
data_folder = "simulations/splat_0.7_de_rq/"

In [3]:
os.path.exists(data_folder + "preds.csv")

True

In [3]:
# get labels
data_path = data_folder + "query_counts.csv"
tools = ["sctype","scsorter","scina","singler", "scpred"]
#tools = ["scsorter","scina","singler"]
ref_path = data_folder + "ref_counts.csv"
ref_label_path = data_folder + "ref_labels.csv"
marker_path = data_folder + "markers.txt"
if os.path.exists(data_folder + "preds.csv"):
    all_labels = pd.read_csv(data_folder + "preds.csv", index_col=0)
    if all_labels.shape[1] != len(tools): 
        all_labels = all_labels[tools]
        #raise Exception("wrong amount of tools in file")
else:
    all_labels = utilities.label_counts(data_path,tools,ref_path,ref_label_path,marker_path)

In [13]:
all_labels = utilities.label_counts(data_path,tools,ref_path,ref_label_path,marker_path)

R[write to console]: Loading required package: Seurat




    an issue that caused a segfault when used with rpy2:
    https://github.com/rstudio/reticulate/pull/1188
    Make sure that you use a version of that package that includes
    the fix.
    

R[write to console]: Attaching SeuratObject

R[write to console]: Attaching sp

R[write to console]: Loading required package: SCINA

R[write to console]: Loading required package: MASS

R[write to console]: Loading required package: gplots

R[write to console]: 
Attaching package: ‘gplots’


R[write to console]: The following object is masked from ‘package:stats’:

    lowess


R[write to console]: Loading required package: scSorter

R[write to console]: Loading required package: dplyr

R[write to console]: 
Attaching package: ‘dplyr’


R[write to console]: The following object is masked from ‘package:MASS’:

    select


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


R[write to console]: Loading required package: SingleR

R[write to console]: Loading required package: SummarizedExperiment

R[write to console]: Loading re

Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 1000
Number of edges: 39615

Running Louvain algorithm...


R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: 

Maximum modularity in 10 random starts: 0.5875
Number of communities: 4
Elapsed time: 0 seconds


R[write to console]: Performing log-normalization

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to conso

●  Extracting feature space for each cell type...
  |                                                  | 0 % ~calculating   |+++++++++++++                                     | 25% ~00s           |+++++++++++++++++++++++++                         | 50% ~00s           |++++++++++++++++++++++++++++++++++++++            | 75% ~00s           |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
DONE!
●  Training models for each cell type...
  |                                                  | 0 % ~calculating  

R[write to console]: Loading required package: ggplot2

R[write to console]: Loading required package: lattice



  |+++++++++++++                                     | 25% ~17s           |+++++++++++++++++++++++++                         | 50% ~10s           |++++++++++++++++++++++++++++++++++++++            | 75% ~05s           |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=18s  
DONE!
●  Matching reference with new dataset...
	 ─ 2000 features present in reference loadings
	 ─ 2000 features shared between reference and new dataset
	 ─ 100% of features in the reference are present in new dataset
●  Aligning new data to reference...


R[write to console]: Harmony 1/20

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write t

●  Classifying cells...
DONE!


In [43]:
all_labels.shape[1]

3

In [4]:
all_labels

scina scsorter  sctype singler  scpred
Cell1001  Group2   Group2  Group1  Group2  Group2
Cell1002  Group4   Group2  Group1  Group4  Group2
Cell1003  Group1   Group4  Group1  Group2     NaN
Cell1004  Group4   Group4  Group4  Group4  Group1
Cell1005  Group1   Group1  Group1  Group1  Group1
...          ...      ...     ...     ...     ...
Cell1996  Group2   Group2  Group4  Group2  Group1
Cell1997  Group1   Group1  Group1  Group1  Group1
Cell1998  Group3   Group3  Group4  Group3  Group3
Cell1999  Group4   Group4  Group1  Group4     NaN
Cell2000  Group2   Group2  Group1  Group2  Group4

[1000 rows x 5 columns]

In [7]:
# read in dataset
X = pd.read_csv(data_path, index_col=0)
X, keep_cells = utilities.preprocess(np.array(X), scale=False)
X.shape

(999, 500)

In [15]:
all_labels = all_labels.loc[keep_cells,:]

In [9]:
_,marker_names = utilities.read_marker_file(marker_path)
marker_names

['Group1', 'Group2', 'Group3', 'Group4']

In [10]:
all_labels['scsorter']

Cell1001    Group2
Cell1002    Group2
Cell1003    Group4
Cell1004    Group4
Cell1005    Group1
             ...  
Cell1996    Group2
Cell1997    Group1
Cell1998    Group3
Cell1999    Group4
Cell2000    Group2
Name: scsorter, Length: 999, dtype: object

In [16]:
all_labels_factored = utilities.factorize_df(all_labels, marker_names)
encoded_labels = utilities.encode_predictions(all_labels_factored)
encoded_labels

array([[0., 5., 0., 0.],
       [0., 3., 0., 2.],
       [1., 2., 0., 1.],
       ...,
       [0., 0., 5., 0.],
       [0., 1., 0., 3.],
       [0., 4., 0., 1.]])

In [11]:
meta_path = data_folder + "query_meta.csv"
metadata = pd.read_csv(meta_path, index_col=0)
real_y = pd.factorize(metadata['Group'], sort=True)[0]
real_y = real_y[keep_cells]
real_y.shape

(999,)

In [61]:
len(real_y[real_y==0])

245

In [17]:
print(utilities.pred_accuracy(all_labels_factored['scina'], real_y))
print(utilities.pred_accuracy(all_labels_factored['sctype'], real_y))
print(utilities.pred_accuracy(all_labels_factored['scsorter'], real_y))
print(utilities.pred_accuracy(all_labels_factored['singler'], real_y))
print(utilities.pred_accuracy(all_labels_factored['scpred'], real_y))


0.792792797088623
0.8138138055801392
0.826826810836792
0.8408408164978027
0.6026026010513306


In [23]:
max_pred = torch.tensor(encoded_labels).max(dim=1)[1]
utilities.pred_accuracy(max_pred, real_y)

0.9389389157295227

In [24]:
confident_labels = utilities.get_consensus_labels(encoded_labels, necessary_vote = 3)
confident_labels.shape

(999,)

In [25]:
train_nodes = np.where(confident_labels != -1)[0]
test_nodes = np.where(confident_labels == -1)[0]
print(np.unique(confident_labels))
print(np.unique(confident_labels[train_nodes]))
print(np.unique(confident_labels[test_nodes]))

[-1.  0.  1.  2.  3.]
[0. 1. 2. 3.]
[-1.]


In [26]:
real_y[test_nodes]

array([3, 0, 3, 0, 0, 0, 1, 2, 2, 2, 3, 0, 1, 1, 3, 2, 0, 1, 2, 3, 2, 1,
       0, 3, 3, 0, 3, 1, 2, 1, 1, 0, 0, 3, 2, 0, 0, 1, 2, 2, 0, 1, 1, 3,
       2, 0, 0, 0, 0, 3, 3, 3, 0, 3, 1, 0, 3, 3, 0, 1, 2, 2, 0, 2, 1, 0,
       3, 1, 0, 0, 2, 1, 3, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 3, 0, 2, 3, 0,
       1, 2, 3, 2, 2, 2, 2, 0, 3, 0, 2, 3, 3, 2, 2, 0, 0, 2, 2, 0, 0, 0,
       3, 1, 2, 2, 0, 0, 2, 0])

In [27]:
print(utilities.pred_accuracy(confident_labels[train_nodes], real_y[train_nodes]))

0.9807037711143494


In [28]:
len(test_nodes)

118

In [21]:
# tool accuracy on test
print(utilities.pred_accuracy(np.array(all_labels_factored['scina'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['sctype'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['scsorter'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['singler'][test_nodes]), real_y[test_nodes]))
print(utilities.pred_accuracy(np.array(all_labels_factored['scpred'][test_nodes]), real_y[test_nodes]))
max_pred = torch.tensor(encoded_labels).max(dim=1)[1]
print(utilities.pred_accuracy(max_pred[test_nodes], real_y[test_nodes]))

0.19491524994373322
0.3644067943096161
0.43220338225364685
0.5932203531265259
0.17796610295772552
0.6271186470985413


In [29]:
dataset  = torch.utils.data.TensorDataset(torch.tensor(X), torch.tensor(confident_labels))
dataloader = torch.utils.data.DataLoader(dataset, batch_size=35, shuffle=True)

test_dataset  = torch.utils.data.TensorDataset(torch.tensor(X), torch.tensor(real_y))
test_dataloader = torch.utils.data.DataLoader(test_dataset, batch_size=35, shuffle=False)

In [30]:
m = GCNModel("configs/2_8.txt", 2, dropout=0.0)

In [31]:
m.train(dataloader, 100)

Loss in epoch 0 = 36.780918
Loss in epoch 10 = 0.142983
Loss in epoch 20 = 0.038523
Loss in epoch 30 = 0.018872
Loss in epoch 40 = 0.008604
Loss in epoch 50 = 0.006198
Loss in epoch 60 = 0.003754
Loss in epoch 70 = 0.002780
Loss in epoch 80 = 0.002784
Loss in epoch 90 = 0.001744


In [32]:
m.validation_metrics(test_dataloader, train_nodes, test_nodes)

(0.9699699878692627,
 array([[222,   4,   1,   5],
        [  0, 267,   1,   0],
        [  2,   4, 223,   5],
        [  2,   5,   1, 257]]),
 0.9807037711143494,
 array([[183,   3,   1,   3],
        [  0, 249,   0,   0],
        [  1,   2, 195,   4],
        [  1,   1,   1, 237]]),
 0.8898305296897888,
 array([[39,  1,  0,  2],
        [ 0, 18,  1,  0],
        [ 1,  2, 28,  1],
        [ 1,  4,  0, 20]]))

In [2]:
data_folders = ["/home/groups/ConradLab/daniel/sharp_sims/splat_0.6_de_rq/", "/home/groups/ConradLab/daniel/sharp_sims/splat_0.7_de_rq/", "/home/groups/ConradLab/daniel/sharp_sims/splat_0.8_de_rq/"]
#data_folders = ["simulations/splat_0.6_de_rq/", "simulations/splat_0.7_de_rq/", "simulations/splat_0.8_de_rq/"]
tools = ["sctype","scsorter","scina","singler", "scpred"]
votes_necessary = 3
model_file = "configs/3_8.txt"
neighbors = 2
batch_size=35
training_epochs=200
random_inits = 5

In [ ]:
results = test_model(data_folders, tools, votes_necessary, model_file, neighbors, batch_size, training_epochs, random_inits)

In [ ]:
results

In [63]:
results

data_name            method  total_accuracy  train_accuracy  \
0  splat_0.6_de_rq               GCN        0.839200        0.944708   
1  splat_0.6_de_rq          Max Col.        0.798000        0.944708   
2  splat_0.6_de_rq  Confident Labels             NaN        0.944708   
3  splat_0.6_de_rq            sctype        0.232000        0.235387   
4  splat_0.6_de_rq          scsorter        0.677000        0.846761   
5  splat_0.6_de_rq             scina        0.467000        0.668246   
6  splat_0.6_de_rq           singler        0.840000        0.913112   
7  splat_0.6_de_rq            scpred        0.503000        0.663507   
0  splat_0.7_de_rq               GCN        0.963764        0.980704   
1  splat_0.7_de_rq          Max Col.        0.938939        0.980704   
2  splat_0.7_de_rq  Confident Labels             NaN        0.980704   
3  splat_0.7_de_rq            sctype        0.411411        0.417707   
4  splat_0.7_de_rq          scsorter        0.826827        0.879682   
5  splat_0.7_de_rq             scina        0.792793        0.872872   
6  splat_0.7_de_rq           singler        0.840841        0.874007   
7  splat_0.7_de_rq            scpred        0.638639        0.700341   
0  splat_0.8_de_rq               GCN        0.987387        0.990702   
1  splat_0.8_de_rq          Max Col.        0.973974        0.990702   
2  splat_0.8_de_rq  Confident Labels             NaN        0.990702   
3  splat_0.8_de_rq            sctype        0.922923        0.934917   
4  splat_0.8_de_rq          scsorter        0.906907        0.923554   
5  splat_0.8_de_rq             scina        0.854855        0.880165   
6  splat_0.8_de_rq           singler        0.870871        0.887397   
7  splat_0.8_de_rq            scpred        0.769770        0.786157   

   test_accuracy  total_sd  train_sd   test_sd  
0       0.657221  0.021076       0.0  0.057428  
1       0.544959  0.000000       0.0  0.000000  
2            NaN  0.000000       0.0  0.000000  
3       0.226158  0.000000       0.0  0.000000  
4       0.384196  0.000000       0.0  0.000000  
5       0.119891  0.000000       0.0  0.000000  
6       0.713896  0.000000       0.0  0.000000  
7       0.226158  0.000000       0.0  0.000000  
0       0.837288  0.004386       0.0  0.037134  
1       0.627119  0.000000       0.0  0.000000  
2            NaN  0.000000       0.0  0.000000  
3       0.364407  0.000000       0.0  0.000000  
4       0.432203  0.000000       0.0  0.000000  
5       0.194915  0.000000       0.0  0.000000  
6       0.593220  0.000000       0.0  0.000000  
7       0.177966  0.000000       0.0  0.000000  
0       0.883871  0.000548       0.0  0.017668  
1       0.451613  0.000000       0.0  0.000000  
2            NaN  0.000000       0.0  0.000000  
3       0.548387  0.000000       0.0  0.000000  
4       0.387097  0.000000       0.0  0.000000  
5       0.064516  0.000000       0.0  0.000000  
6       0.354839  0.000000       0.0  0.000000  
7       0.258065  0.000000       0.0  0.000000