In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from test_model import test_model
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sc_sharp import scSHARP
import utilities

/home/users/lewinsda/.conda/envs/daniel_thesis_2/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
data_folders = ["/home/groups/ConradLab/daniel/sharp_data/sharp_sims_test/splat_0.8_test_031823/"]
tools = ["sctype","scsorter","scina", "singler", "scpred"]
votes_necessary = .51
model_file = "configs/2_40.txt"
neighbors = 2
batch_size=20
training_epochs=150
random_inits = 5
counts="query_counts.csv"
meta="query_meta.csv"
meta_col = "Group"

In [3]:
results = test_model(data_folders, tools, votes_necessary, model_file, neighbors, batch_size, training_epochs, random_inits, counts=counts, meta=meta, meta_col=meta_col)
results

Parameter containing:
tensor([[-0.0002,  0.0170, -0.0260,  ..., -0.0102,  0.0001, -0.0061],
        [-0.0027, -0.0247, -0.0002,  ...,  0.0012, -0.0096,  0.0238],
        [ 0.0175,  0.0057,  0.0048,  ..., -0.0144, -0.0125, -0.0265],
        ...,
        [-0.0072, -0.0208, -0.0296,  ..., -0.0211, -0.0240, -0.0088],
        [-0.0279, -0.0064, -0.0075,  ...,  0.0198, -0.0039,  0.0138],
        [ 0.0019,  0.0309,  0.0283,  ...,  0.0084,  0.0315,  0.0004]],
       device='cuda:0', requires_grad=True)
Loss in epoch 0 = 57.175819
Loss in epoch 10 = 0.045323
Loss in epoch 20 = 0.016790
Loss in epoch 30 = 0.008831
Loss in epoch 40 = 0.002244
Loss in epoch 50 = 0.001721
Loss in epoch 60 = 0.001061
Loss in epoch 70 = 0.000661
Loss in epoch 80 = 0.000557
Loss in epoch 90 = 0.000314
Loss in epoch 100 = 0.000255
Loss in epoch 110 = 0.000141
Loss in epoch 120 = 0.000143
Loss in epoch 130 = 0.000094
Loss in epoch 140 = 0.000067
Parameter containing:
tensor([[ 0.0163, -0.0140, -0.0061,  ..., -0.0271, -0

/home/users/lewinsda/scSHARP/utilities.py:187: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


data_name            method  total_accuracy  train_accuracy  \
0  splat_0.8_test_031823               GCN        0.960721        0.972618   
1  splat_0.8_test_031823          Max Col.        0.911824        0.972618   
2  splat_0.8_test_031823  Confident Labels             NaN        0.972618   
3  splat_0.8_test_031823            sctype        0.798597        0.845564   
4  splat_0.8_test_031823          scsorter        0.886774        0.933187   
5  splat_0.8_test_031823             scina        0.587174        0.639650   
6  splat_0.8_test_031823           singler        0.851703        0.858708   
7  splat_0.8_test_031823            scpred        0.710421        0.753560   
8  splat_0.8_test_031823         Tool Avg.        0.766934        0.806134   

   test_accuracy  total_sd  train_sd   test_sd  
0       0.832941  0.002955  0.000000  0.034701  
1       0.258824  0.000000  0.000000  0.000000  
2            NaN  0.000000  0.000000  0.000000  
3       0.294118  0.000000  0.000000  0.000000  
4       0.388235  0.000000  0.000000  0.000000  
5       0.023529  0.000000  0.000000  0.000000  
6       0.776471  0.000000  0.000000  0.000000  
7       0.247059  0.000000  0.000000  0.000000  
8       0.345882  0.120475  0.112852  0.275480

In [3]:
results = test_model(data_folders, tools, votes_necessary, model_file, neighbors, batch_size, training_epochs, random_inits, counts=counts, meta=meta, meta_col=meta_col)
results

Parameter containing:
tensor([[-0.0002,  0.0170, -0.0260,  ..., -0.0102,  0.0001, -0.0061],
        [-0.0027, -0.0247, -0.0002,  ...,  0.0012, -0.0096,  0.0238],
        [ 0.0175,  0.0057,  0.0048,  ..., -0.0144, -0.0125, -0.0265],
        ...,
        [-0.0072, -0.0208, -0.0296,  ..., -0.0211, -0.0240, -0.0088],
        [-0.0279, -0.0064, -0.0075,  ...,  0.0198, -0.0039,  0.0138],
        [ 0.0019,  0.0309,  0.0283,  ...,  0.0084,  0.0315,  0.0004]],
       requires_grad=True)
Loss in epoch 0 = 57.149784
Loss in epoch 10 = 0.045778
Loss in epoch 20 = 0.059147
Loss in epoch 30 = 0.016786
Loss in epoch 40 = 0.002143
Loss in epoch 50 = 0.001587
Loss in epoch 60 = 0.001191
Loss in epoch 70 = 0.000687
Loss in epoch 80 = 0.001457
Loss in epoch 90 = 0.000339
Loss in epoch 100 = 0.000249
Loss in epoch 110 = 0.000151
Loss in epoch 120 = 0.000144
Loss in epoch 130 = 0.000115
Loss in epoch 140 = 0.000069
Parameter containing:
tensor([[ 0.0163, -0.0140, -0.0061,  ..., -0.0271, -0.0100,  0.0138],


/home/users/lewinsda/scSHARP/utilities.py:187: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


data_name            method  total_accuracy  train_accuracy  \
0  splat_0.8_test_031823               GCN        0.960721        0.972618   
1  splat_0.8_test_031823          Max Col.        0.911824        0.972618   
2  splat_0.8_test_031823  Confident Labels             NaN        0.972618   
3  splat_0.8_test_031823            sctype        0.798597        0.845564   
4  splat_0.8_test_031823          scsorter        0.886774        0.933187   
5  splat_0.8_test_031823             scina        0.587174        0.639650   
6  splat_0.8_test_031823           singler        0.851703        0.858708   
7  splat_0.8_test_031823            scpred        0.710421        0.753560   
8  splat_0.8_test_031823         Tool Avg.        0.766934        0.806134   

   test_accuracy  total_sd  train_sd   test_sd  
0       0.832941  0.002172  0.000000  0.025505  
1       0.258824  0.000000  0.000000  0.000000  
2            NaN  0.000000  0.000000  0.000000  
3       0.294118  0.000000  0.000000  0.000000  
4       0.388235  0.000000  0.000000  0.000000  
5       0.023529  0.000000  0.000000  0.000000  
6       0.776471  0.000000  0.000000  0.000000  
7       0.247059  0.000000  0.000000  0.000000  
8       0.345882  0.120475  0.112852  0.275480

In [3]:
results = test_model(data_folders, tools, votes_necessary, model_file, neighbors, batch_size, training_epochs, random_inits, counts=counts, meta=meta, meta_col=meta_col)
results

Loss in epoch 0 = 57.149708
Loss in epoch 10 = 0.045777
Loss in epoch 20 = 0.060305
Loss in epoch 30 = 0.016872
Loss in epoch 40 = 0.002145
Loss in epoch 50 = 0.001576
Loss in epoch 60 = 0.001173
Loss in epoch 70 = 0.000690
Loss in epoch 80 = 0.001564
Loss in epoch 90 = 0.000342
Loss in epoch 100 = 0.000247
Loss in epoch 110 = 0.000151
Loss in epoch 120 = 0.000144
Loss in epoch 130 = 0.000123
Loss in epoch 140 = 0.000068
Loss in epoch 0 = 59.194626
Loss in epoch 10 = 0.053449
Loss in epoch 20 = 0.012053
Loss in epoch 30 = 0.005758
Loss in epoch 40 = 0.002978
Loss in epoch 50 = 0.001557
Loss in epoch 60 = 0.001381
Loss in epoch 70 = 0.000644
Loss in epoch 80 = 0.000616
Loss in epoch 90 = 0.000307
Loss in epoch 100 = 0.000266
Loss in epoch 110 = 0.000213
Loss in epoch 120 = 0.000129
Loss in epoch 130 = 0.000105
Loss in epoch 140 = 0.000078
Loss in epoch 0 = 57.983601
Loss in epoch 10 = 0.073408
Loss in epoch 20 = 0.012047
Loss in epoch 30 = 0.004465
Loss in epoch 40 = 0.002221
Loss in ep

/home/users/lewinsda/scSHARP/utilities.py:187: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return float((torch.tensor(preds) == torch.tensor(real)).type(torch.FloatTensor).mean().numpy())


data_name            method  total_accuracy  train_accuracy  \
0  splat_0.8_test_031823               GCN        0.960721        0.972618   
1  splat_0.8_test_031823          Max Col.        0.911824        0.972618   
2  splat_0.8_test_031823  Confident Labels             NaN        0.972618   
3  splat_0.8_test_031823            sctype        0.798597        0.845564   
4  splat_0.8_test_031823          scsorter        0.886774        0.933187   
5  splat_0.8_test_031823             scina        0.587174        0.639650   
6  splat_0.8_test_031823           singler        0.851703        0.858708   
7  splat_0.8_test_031823            scpred        0.710421        0.753560   
8  splat_0.8_test_031823         Tool Avg.        0.766934        0.806134   

   test_accuracy  total_sd  train_sd   test_sd  
0       0.832941  0.002172  0.000000  0.025505  
1       0.258824  0.000000  0.000000  0.000000  
2            NaN  0.000000  0.000000  0.000000  
3       0.294118  0.000000  0.000000  0.000000  
4       0.388235  0.000000  0.000000  0.000000  
5       0.023529  0.000000  0.000000  0.000000  
6       0.776471  0.000000  0.000000  0.000000  
7       0.247059  0.000000  0.000000  0.000000  
8       0.345882  0.120475  0.112852  0.275480